version: '3.8'

services:
  bulkupload-app:
    build: .
    container_name: bulkuploadpipeline
    ports:
      - "8080:8080"
    environment:
      MONGO_HOST: host.docker.internal
      MONGO_PORT: 27018
    volumes:
      - ./uploads:/app/uploads
