spring:
  application:
    name: bulkuploadpipeline

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  data:
    mongodb:
      host: localhost
      port: 27018
      database: bulkuploadpipeline

  task:
    execution:
      pool:
        core-size: 5
        max-size: 10

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
